# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Peter Geyser
tagline:          'Developer Portfolio'
description:      ''
url:              https://ppgeyser.github.io/
baseurl:          https://ppgeyser.github.io/

author:
  name:           'Peter Geyser'
  url:            www.linkedin.com/in/pgeyser

paginate:         

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ppgeyser
